# Generated by Django 5.0.1 on 2024-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='teams')),
                ('stadium', models.CharField(max_length=250)),
                ('coach', models.CharField(max_length=250)),
            ],
        ),
    ]
