# Generated by Django 5.0.1 on 2024-02-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team1', models.CharField(max_length=250)),
                ('name_team2', models.CharField(max_length=250)),
                ('data', models.DateField()),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
    ]
