# Generated by Django 5.0.1 on 2024-02-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_live', '0002_match_remove_team_coach_remove_team_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score',
            new_name='score_team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='name_team1',
        ),
        migrations.AddField(
            model_name='match',
            name='meciuri_gazda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='football_live.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='score_team2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='name_team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meciuri_oaspeti', to='football_live.team'),
        ),
    ]
