# Generated by Django 5.0.1 on 2024-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_live', '0004_remove_match_meciuri_gazda_remove_match_name_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='log_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
