# Generated by Django 5.0.1 on 2024-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_live', '0005_match_log_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('log_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='log_url',
        ),
    ]
