# Generated by Django 5.0.1 on 2024-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_live', '0007_remove_team_log_url_team_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='minute',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='data',
            field=models.DateTimeField(verbose_name='utcDate'),
        ),
    ]
