# Generated by Django 5.0.1 on 2024-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_live', '0008_remove_match_away_team_remove_match_home_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='teams',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='competition',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='live_match',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='data',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(default='', max_length=255),
        ),
    ]
